
title: My Resume
url: ''
baseurl: '' #change ivt according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Joseph Luccisano 
tagline: Full Stack Developer
pic: me.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:	
phone:
website: jluccisano.github.io #do not add http://
linkedin: jluccisano
github: jluccisano
twitter: '@joluccisano'

# Analytics
google_analytics: 'UA-90396820-1'

#Update all the sections by editing the files inside _includes folder.
